# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '4b43accf-a0fe-4d10-8ae6-d8fc6222177d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg-VM'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/oworldbankru/AzureRmPipeline-repo/main/azuredeploy.json'
    overrideParameters: '-projectName vishal0700'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
